# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final4/piano_final/piano_final.srcs/sources_1/ip/silence/silence.xci
# IP: The module: 'silence' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final4/piano_final/piano_final.srcs/sources_1/ip/silence/silence_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'silence'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final4/piano_final/piano_final.srcs/sources_1/ip/silence/silence.xci
# IP: The module: 'silence' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final4/piano_final/piano_final.srcs/sources_1/ip/silence/silence_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'silence'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
