# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/piano_final/piano_final.cache/wt [current_project]
set_property parent.project_path C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/piano_final/piano_final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/piano_final/piano_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final3/photos_coe/silence.coe
add_files C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/photos_coe/silence.coe
read_verilog -library xil_defaultlib {
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Auto_play.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Bar.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Clkdiv.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Display_melody.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Free_play.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Generate_Melody.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Key_dejitter.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Press_signal.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Select_frequency.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Vga_picture.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/vga_640x480.v
  C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/Piano_top.v
}
read_ip -quiet C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/piano_final/piano_final.srcs/sources_1/ip/silence/silence.xci
set_property used_in_implementation false [get_files -all c:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/piano_final/piano_final.srcs/sources_1/ip/silence/silence_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/piano_cntr.xdc
set_property used_in_implementation false [get_files C:/Users/Winter/Desktop/vivado/Homework/Week8-10/piano_final5/Code/piano_cntr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Piano_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Piano_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Piano_top_utilization_synth.rpt -pb Piano_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
