set_property PACKAGE_PIN W7 [get_ports {a_to_g[6]}]					
set_property PACKAGE_PIN W6 [get_ports {a_to_g[5]}]					
set_property PACKAGE_PIN U8 [get_ports {a_to_g[4]}]					
set_property PACKAGE_PIN V8 [get_ports {a_to_g[3]}]				
set_property PACKAGE_PIN U5 [get_ports {a_to_g[2]}]					
set_property PACKAGE_PIN V5 [get_ports {a_to_g[1]}]					
set_property PACKAGE_PIN U7 [get_ports {a_to_g[0]}]					

set_property PACKAGE_PIN U2 [get_ports {AN[0]}]					
set_property PACKAGE_PIN U4 [get_ports {AN[1]}]					
set_property PACKAGE_PIN V4 [get_ports {AN[2]}]					
set_property PACKAGE_PIN W4 [get_ports {AN[3]}]					

#前四个选择开关
set_property PACKAGE_PIN W2 [get_ports {x[0]}]					
set_property PACKAGE_PIN U1 [get_ports {x[1]}]					
set_property PACKAGE_PIN T1 [get_ports {x[2]}]					
set_property PACKAGE_PIN R2 [get_ports {x[3]}]					


set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x[3]}]